### ISSUE TITLE
Cannot compile the rev. shell.

### ISSUE THREAD

**Issue by StillNoob** [passthehashbrowns/Haskell-Reverse-Shell#1]
The following error is displayed when trying to compile ths .hs file.
` Could not find module ‘Network.Socket’
    Use -v to see a list of the files searched for.
  |
1 | import Network.Socket hiding (send, sendTo, recv, recvFrom)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

jdoodle.hs:2:1: error:
    Could not find module ‘Network.Socket.ByteString’
    Use -v to see a list of the files searched for.
  |
2 | import Network.Socket.ByteString (send, recv)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by passthehashbrowns** [comment]
Since Network.Socket is not included in the Haskell Standard Prelude, you'll need to install it using Cabal. 

https://wiki.haskell.org/Cabal/How_to_install_a_Cabal_package
